### ISSUE TITLE
The include paths are windows specific....

### ISSUE THREAD

**Issue by frohro** [bluehash/MSP432Launchpad#1]
Hi Gerard,

Thanks for this nice tutorial software on getting the backchannel UART going.  I am using Ubuntu 15.10, and found that it would not compile because you have some C: and E: include file paths set that don't generalize when the wizard tries to import them in Linux.  I found that I had to follow the procedure detailed on e2e [here](https://e2e.ti.com/support/microcontrollers/msp430/f/166/p/490640/1772213#1772213).  It is now working for me, but it took some effort.

Thanks,

Rob

**Comment by bluehash** [comment]
Hi Rob,
Thanks for taking the time to let me know. I'll put a note in the Readme.
